#!/bin/sh -e

ld="`head -n 1 conf-ld`"
strip="`head -n 1 conf-stripbins`"
test -n "$strip" || strip="echo Not stripping"

cat warn-auto.sh
echo 'main="$1" ; shift'
echo "$ld " | tr -d '\n'
test -f flag-allstatic || { echo '-Wl,--allow-shlib-undefined ' | tr -d '\n' ; ./stupid < path-library.so | while read dir ; do echo "-L $dir " | tr -d '\n' ; done ; }
./stupid < path-library | while read dir ; do echo "-L $dir " | tr -d '\n' ; done
echo '-L . -o "$main" "$main".o ${1+"$@"}'
echo exec "$strip" '"$main"'
