#!/bin/sh
s=`cat conf-sp_root`
c=`cat conf-callpath`
h=`cat conf-home`
n=`cat conf-name`
v=`cat conf-version`
exec sed s\|\\\$SP_ROOT\|$s\|g\;s\|\\\$PACKAGE_HOME\|$h\|g\;s\|\\\$PACKAGE_NAME\|$n\|g\;s\|\\\$PACKAGE_VERSION\|$v\|g\;s\|\\\$PACKAGE_CALLPATH\|$c\|g
