#!/bin/sh -e
# Public domain.

umask 022
test -d package -a -d src -a -d conf-compile || { echo 'Wrong working directory.' ; exit 100 ; }

exec rm -rf compile command include library library.so sysdeps
