#!/bin/sh -e
# Public domain.

umask 022
test -d package -a -d src -a -d conf-compile || { echo 'Wrong working directory.' ; exit 100 ; }

package/compile
package/upgrade
package/export
exec package/run
