#!/bin/sh -e
# Public domain.

umask 022
test -d package -a -d src -a -d conf-compile || { echo 'Wrong working directory.' ; exit 100 ; }

for i in `cat package/subsystems` ; do package/compilesub "$i" ; done
